version: "3.9"
services:
  app:
    image: python-tiny-api
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    command: uvicorn application:app --host=0.0.0.0 --port=5000 --reload